#!/usr/bin/env python3
"""
Seed site_content table with hardcoded content from templates.

Idempotent: uses INSERT ... ON CONFLICT (key) DO UPDATE.

Usage:
    python scripts/seed_site_content.py
"""

import os
import psycopg2

DB_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://postgres:postgres@localhost:5432/neodemos",
)

# Each tuple: (key, section, label, content_type, value, help_text, sort_order)
SEED_DATA = [
    # ── Section: landing (from search.html) ──
    (
        "landing.hero_placeholder",
        "landing",
        "Zoekveld placeholder",
        "text",
        "Stel uw eigen vraag...",
        "Placeholder-tekst in het zoekveld op de landingspagina",
        10,
    ),
    (
        "landing.example_query_1",
        "landing",
        "Voorbeeldvraag 1",
        "text",
        "Heeft het college haar beloftes waargemaakt?",
        "Eerste voorbeeldvraag onder het zoekveld",
        20,
    ),
    (
        "landing.example_query_2",
        "landing",
        "Voorbeeldvraag 2",
        "text",
        "Hoe stemden partijen over woningbouw?",
        "Tweede voorbeeldvraag onder het zoekveld",
        30,
    ),
    (
        "landing.example_query_3",
        "landing",
        "Voorbeeldvraag 3",
        "text",
        "Welke moties over klimaat zijn aangenomen sinds 2020?",
        "Derde voorbeeldvraag onder het zoekveld",
        40,
    ),
    (
        "landing.example_queries_label",
        "landing",
        "Label voorbeeldvragen",
        "text",
        "Of probeer:",
        "Tekst boven de voorbeeldvragen",
        50,
    ),
    (
        "landing.stat_documents",
        "landing",
        "Statistiek documenten",
        "text",
        "90.000+ documenten",
        "Aantal documenten in de hero-balk",
        60,
    ),
    (
        "landing.stat_years",
        "landing",
        "Statistiek jaren",
        "text",
        "24 jaar",
        "Aantal jaren in de hero-balk",
        70,
    ),
    (
        "landing.stat_city",
        "landing",
        "Statistiek stad",
        "text",
        "Rotterdam",
        "Stadsnaam in de hero-balk",
        80,
    ),
    (
        "landing.stat_open",
        "landing",
        "Statistiek open data",
        "text",
        "Open brondata",
        "Open-data label in de hero-balk",
        90,
    ),
    (
        "landing.nudge_title",
        "landing",
        "Account-nudge titel",
        "text",
        "Wist u dat u uw zoekopdrachten kunt bewaren?",
        "Titel van de account-aanmaak banner",
        100,
    ),
    (
        "landing.nudge_text",
        "landing",
        "Account-nudge tekst",
        "textarea",
        "Maak een gratis account en bewaar uw zoekgeschiedenis, stel uw partijlens in, en exporteer analyses naar Word.",
        "Beschrijving in de account-aanmaak banner",
        110,
    ),
    (
        "landing.nudge_cta",
        "landing",
        "Account-nudge knop",
        "text",
        "Gratis account aanmaken",
        "Call-to-action tekst op de knop",
        120,
    ),
    (
        "landing.mcp_nudge",
        "landing",
        "MCP-nudge tekst",
        "textarea",
        "Tip: gebruik NeoDemos rechtstreeks in Claude, ChatGPT of Cursor voor diepere analyses. Werkt ook met Ollama.",
        "Tekst van de MCP-integratie banner",
        130,
    ),
    (
        "landing.demo_mobile_summary",
        "landing",
        "Demo mobiel samenvatting",
        "text",
        "Bekijk voorbeeld",
        "Tekst op de inklapbare demo-sectie (mobiel)",
        140,
    ),

    # ── Section: over (from over.html) ──
    (
        "over.hero_title",
        "over",
        "Hero titel",
        "text",
        "Over NeoDemos",
        "Titel in de hero-afbeelding",
        10,
    ),
    (
        "over.hero_subtitle",
        "over",
        "Hero ondertitel",
        "text",
        "De raadsinformatie was er altijd al. Wij maken haar vindbaar.",
        "Ondertitel in de hero-afbeelding",
        20,
    ),
    (
        "over.founder_quote",
        "over",
        "Oprichter-citaat",
        "textarea",
        "Als raadslid had ik toegang tot alles \u2014 en toch klikte ik me een weg door honderden losse PDF\u2019s om \u00e9\u00e9n antwoord te vinden. Dat kon beter.",
        "Citaat van de oprichter in de founder-sectie",
        30,
    ),
    (
        "over.founder_cite",
        "over",
        "Oprichter-naam",
        "text",
        "\u2014 Dennis Tak, oud-raadslid Rotterdam",
        "Naamsvermelding bij het oprichter-citaat",
        40,
    ),
    (
        "over.mission_title",
        "over",
        "Missie titel",
        "text",
        "Democratie werkt alleen als burgers en raadsleden dezelfde informatie hebben",
        "Koptekst van de missie-sectie",
        50,
    ),
    (
        "over.mission_p1",
        "over",
        "Missie alinea 1",
        "textarea",
        "De Rotterdamse gemeenteraad produceert duizenden documenten per jaar: moties, amendementen, notulen, begrotingen, commissieverslagen. Die zijn allemaal openbaar \u2014 maar in de praktijk ontoegankelijk. Ze staan verspreid over portalen, in PDF-formaat, zonder samenhang.",
        "Eerste alinea van de missie-uitleg",
        60,
    ),
    (
        "over.mission_p2",
        "over",
        "Missie alinea 2",
        "textarea",
        "NeoDemos maakt die informatie doorzoekbaar, analyseerbaar en begrijpelijk. Niet door te versimpelen, maar door verbanden zichtbaar te maken die er altijd al waren.",
        "Tweede alinea van de missie-uitleg",
        70,
    ),
    (
        "over.origin_title",
        "over",
        "Oorsprong titel",
        "text",
        "Hoe het begon",
        "Koptekst van de oorsprong-sectie",
        80,
    ),
    (
        "over.origin_p1",
        "over",
        "Oorsprong alinea 1",
        "textarea",
        "NeoDemos is ontstaan uit frustratie. Als gemeenteraadslid in Rotterdam merkte oprichter Dennis Tak dat essenti\u00eble informatie weliswaar openbaar was, maar in de praktijk onvindbaar. Dossiers die drie jaar eerder waren behandeld, beloftes uit coalitieakkoorden, stemmingen over vergelijkbare moties \u2014 het kostte uren om de puzzelstukjes bij elkaar te zoeken.",
        "Eerste alinea van het oorsprongverhaal",
        90,
    ),
    (
        "over.origin_p2",
        "over",
        "Oorsprong alinea 2",
        "textarea",
        "Dat moest anders. NeoDemos combineert meer dan 90.000 raadsdocumenten uit de periode 2002 tot heden met kunstmatige intelligentie, zodat elke vraag over wat de gemeente deed, besloot of beloofde direct antwoord krijgt \u2014 met bronvermelding.",
        "Tweede alinea van het oorsprongverhaal",
        100,
    ),
    (
        "over.testimonial_quote",
        "over",
        "Testimonial citaat",
        "textarea",
        "Dit spaarde me twee uur voorbereiding.",
        "Citaat in de testimonial-sectie",
        110,
    ),
    (
        "over.testimonial_cite",
        "over",
        "Testimonial naamsvermelding",
        "text",
        "\u2014 Raadslid, Rotterdam",
        "Bron van het testimonial-citaat",
        120,
    ),
    (
        "over.audience_raadsleden_title",
        "over",
        "Doelgroep: raadsleden titel",
        "text",
        "Raadsleden & fractiemedewerkers",
        "Titel van de raadsleden-doelgroepkaart",
        130,
    ),
    (
        "over.audience_raadsleden_text",
        "over",
        "Doelgroep: raadsleden tekst",
        "textarea",
        "Snellere dossiervoorbereiding, inzicht in stemgedrag en beleidscontinuiteit.",
        "Beschrijving van de raadsleden-doelgroepkaart",
        140,
    ),
    (
        "over.audience_journalisten_title",
        "over",
        "Doelgroep: journalisten titel",
        "text",
        "Journalisten",
        "Titel van de journalisten-doelgroepkaart",
        150,
    ),
    (
        "over.audience_journalisten_text",
        "over",
        "Doelgroep: journalisten tekst",
        "textarea",
        "Feitelijke basis voor onderzoeksverhalen, met directe verwijzing naar brondocumenten.",
        "Beschrijving van de journalisten-doelgroepkaart",
        160,
    ),
    (
        "over.audience_ambtenaren_title",
        "over",
        "Doelgroep: ambtenaren titel",
        "text",
        "Ambtenaren",
        "Titel van de ambtenaren-doelgroepkaart",
        170,
    ),
    (
        "over.audience_ambtenaren_text",
        "over",
        "Doelgroep: ambtenaren tekst",
        "textarea",
        "Overzicht van eerdere besluiten en toezeggingen bij beleidsvoorbereiding.",
        "Beschrijving van de ambtenaren-doelgroepkaart",
        180,
    ),
    (
        "over.audience_bewoners_title",
        "over",
        "Doelgroep: bewoners titel",
        "text",
        "Betrokken bewoners",
        "Titel van de bewoners-doelgroepkaart",
        190,
    ),
    (
        "over.audience_bewoners_text",
        "over",
        "Doelgroep: bewoners tekst",
        "textarea",
        "Begrijpelijke antwoorden op vragen over wat de gemeente heeft gedaan en besloten.",
        "Beschrijving van de bewoners-doelgroepkaart",
        200,
    ),

    # ── Section: technologie (from technologie.html) ──
    (
        "technologie.hero_title",
        "technologie",
        "Hero titel",
        "text",
        "Technologie",
        "Titel in de hero-afbeelding",
        10,
    ),
    (
        "technologie.hero_subtitle",
        "technologie",
        "Hero ondertitel",
        "text",
        "Uw data, uw AI",
        "Ondertitel in de hero-afbeelding",
        20,
    ),
    (
        "technologie.eu_title",
        "technologie",
        "Europees sectie titel",
        "text",
        "Volledig Europees",
        "Koptekst van de EU-soevereiniteit sectie",
        30,
    ),
    (
        "technologie.eu_intro",
        "technologie",
        "Europees sectie intro",
        "textarea",
        "NeoDemos is gebouwd op Europese infrastructuur. Geen afhankelijkheid van Amerikaanse clouddiensten, geen blootstelling aan de CLOUD Act, geen data die de EU verlaat.",
        "Inleidende tekst van de EU-soevereiniteit sectie",
        40,
    ),
    (
        "technologie.eu_hetzner_title",
        "technologie",
        "Hetzner kaart titel",
        "text",
        "Hetzner, Duitsland",
        "Titel van de Hetzner-kaart",
        50,
    ),
    (
        "technologie.eu_hetzner_text",
        "technologie",
        "Hetzner kaart tekst",
        "textarea",
        "Servers in Duitse datacenters. Europese jurisdictie, GDPR-compliant.",
        "Beschrijving op de Hetzner-kaart",
        60,
    ),
    (
        "technologie.eu_nebius_title",
        "technologie",
        "Nebius kaart titel",
        "text",
        "Nebius, EU AI",
        "Titel van de Nebius-kaart",
        70,
    ),
    (
        "technologie.eu_nebius_text",
        "technologie",
        "Nebius kaart tekst",
        "textarea",
        "AI-inferentie via Europese providers. Geen data naar OpenAI of Google servers.",
        "Beschrijving op de Nebius-kaart",
        80,
    ),
    (
        "technologie.eu_cloud_act_title",
        "technologie",
        "CLOUD Act kaart titel",
        "text",
        "Geen US CLOUD Act",
        "Titel van de CLOUD Act-kaart",
        90,
    ),
    (
        "technologie.eu_cloud_act_text",
        "technologie",
        "CLOUD Act kaart tekst",
        "textarea",
        "Geen Amerikaanse partij kan uw gegevens opvragen via juridische achterdeur.",
        "Beschrijving op de CLOUD Act-kaart",
        100,
    ),
    (
        "technologie.security_title",
        "technologie",
        "Veiligheid titel",
        "text",
        "Veiligheidsgaranties",
        "Koptekst van de veiligheidssectie",
        110,
    ),
    (
        "technologie.security_checklist",
        "technologie",
        "Veiligheid checklist",
        "textarea",
        "Alleen publieke brondata \u2014 geen vertrouwelijke documenten\n"
        "Geen tracking of profilering van gebruikers\n"
        "Lokale AI mogelijk via Ollama, LM Studio of Open WebUI\n"
        "Audit trail op elk antwoord \u2014 elke bewering herleidbaar naar brondocument\n"
        "EU AI Act conform \u2014 transparant over wat AI doet en niet doet\n"
        "Uw vragen trainen geen AI-modellen",
        "Eén item per regel. Wordt als lijst weergegeven.",
        120,
    ),
    (
        "technologie.local_ai_title",
        "technologie",
        "Lokale AI titel",
        "text",
        "Lokale AI: uw data verlaat nooit uw netwerk",
        "Koptekst van de lokale AI-sectie",
        130,
    ),
    (
        "technologie.local_ai_intro",
        "technologie",
        "Lokale AI intro",
        "textarea",
        "NeoDemos werkt via het Model Context Protocol (MCP), een open standaard die u in staat stelt uw eigen AI-assistent te verbinden. Dat betekent dat u kunt kiezen waar uw vragen worden verwerkt:",
        "Inleidende tekst van de lokale AI-sectie",
        140,
    ),
    (
        "technologie.model_independence_title",
        "technologie",
        "Modelonafhankelijk titel",
        "text",
        "Modelonafhankelijk",
        "Koptekst van de modelonafhankelijkheid-sectie",
        150,
    ),
    (
        "technologie.model_independence_text",
        "technologie",
        "Modelonafhankelijk tekst",
        "textarea",
        "NeoDemos is niet gebonden aan \u00e9\u00e9n AI-provider. Via MCP werkt het platform met elk compatibel model:",
        "Uitleg over modelonafhankelijkheid",
        160,
    ),
    (
        "technologie.architecture_title",
        "technologie",
        "Architectuur titel",
        "text",
        "Architectuur in het kort",
        "Koptekst van de architectuur-sectie",
        170,
    ),
    (
        "technologie.architecture_intro",
        "technologie",
        "Architectuur intro",
        "textarea",
        "NeoDemos combineert drie lagen om betrouwbare antwoorden te genereren:",
        "Inleidende tekst van de architectuur-sectie",
        180,
    ),
    (
        "technologie.arch_step1_title",
        "technologie",
        "Architectuur stap 1 titel",
        "text",
        "Brondata",
        "Titel van architectuurstap 1",
        190,
    ),
    (
        "technologie.arch_step1_text",
        "technologie",
        "Architectuur stap 1 tekst",
        "textarea",
        "90.000+ documenten van de Rotterdamse gemeenteraad, gestructureerd en doorzoekbaar gemaakt met vector- en full-text search.",
        "Beschrijving van architectuurstap 1",
        200,
    ),
    (
        "technologie.arch_step2_title",
        "technologie",
        "Architectuur stap 2 titel",
        "text",
        "Retrieval",
        "Titel van architectuurstap 2",
        210,
    ),
    (
        "technologie.arch_step2_text",
        "technologie",
        "Architectuur stap 2 tekst",
        "textarea",
        "Elke vraag wordt beantwoord op basis van de meest relevante documentfragmenten. Geen hallucinatie \u2014 alleen feiten uit brondocumenten.",
        "Beschrijving van architectuurstap 2",
        220,
    ),
    (
        "technologie.arch_step3_title",
        "technologie",
        "Architectuur stap 3 titel",
        "text",
        "Transparantie",
        "Titel van architectuurstap 3",
        230,
    ),
    (
        "technologie.arch_step3_text",
        "technologie",
        "Architectuur stap 3 tekst",
        "textarea",
        "Elk antwoord bevat bronverwijzingen. Klik op een citaat om het originele document te lezen.",
        "Beschrijving van architectuurstap 3",
        240,
    ),

    # ── Section: methodologie (from methodologie.html) ──
    (
        "methodologie.hero_title",
        "methodologie",
        "Hero titel",
        "text",
        "Methodologie",
        "Titel in de hero-afbeelding",
        10,
    ),
    (
        "methodologie.hero_subtitle",
        "methodologie",
        "Hero ondertitel",
        "text",
        "Hoe NeoDemos werkt \u2014 en waar de grenzen liggen",
        "Ondertitel in de hero-afbeelding",
        20,
    ),
    (
        "methodologie.steps_title",
        "methodologie",
        "Stappen titel",
        "text",
        "Drie stappen",
        "Koptekst van de stappen-sectie",
        30,
    ),
    (
        "methodologie.step1_title",
        "methodologie",
        "Stap 1 titel",
        "text",
        "Zoeken",
        "Titel van stap 1",
        40,
    ),
    (
        "methodologie.step1_text",
        "methodologie",
        "Stap 1 tekst",
        "textarea",
        "Uw vraag wordt omgezet naar een zoekopdracht over 90.000+ raadsdocumenten. Zowel full-text search als semantische vectorzoekopdrachten worden gecombineerd om de meest relevante fragmenten te vinden.",
        "Beschrijving van stap 1",
        50,
    ),
    (
        "methodologie.step2_title",
        "methodologie",
        "Stap 2 titel",
        "text",
        "Analyseren",
        "Titel van stap 2",
        60,
    ),
    (
        "methodologie.step2_text",
        "methodologie",
        "Stap 2 tekst",
        "textarea",
        "De gevonden fragmenten worden door een AI-model geanalyseerd. Het model synthetiseert informatie uit meerdere bronnen tot een samenhangend antwoord. Het model mag alleen feiten uit de aangeleverde bronnen gebruiken.",
        "Beschrijving van stap 2",
        70,
    ),
    (
        "methodologie.step3_title",
        "methodologie",
        "Stap 3 titel",
        "text",
        "Verwijzen",
        "Titel van stap 3",
        80,
    ),
    (
        "methodologie.step3_text",
        "methodologie",
        "Stap 3 tekst",
        "textarea",
        "Elke bewering in het antwoord wordt voorzien van een bronverwijzing. U kunt doorklikken naar het originele document om de context te controleren.",
        "Beschrijving van stap 3",
        90,
    ),
    (
        "methodologie.sources_title",
        "methodologie",
        "Bronnen titel",
        "text",
        "Onze bronnen",
        "Koptekst van de bronnen-sectie",
        100,
    ),
    (
        "methodologie.sources_intro",
        "methodologie",
        "Bronnen intro",
        "textarea",
        "NeoDemos indexeert publiek beschikbare documenten van de Rotterdamse gemeenteraad via Open Raadsinformatie:",
        "Inleidende tekst van de bronnen-sectie",
        110,
    ),
    (
        "methodologie.stat_documents",
        "methodologie",
        "Statistiek documenten",
        "text",
        "90.000+",
        "Aantal documenten in de bronnen-statistieken",
        120,
    ),
    (
        "methodologie.stat_period",
        "methodologie",
        "Statistiek periode",
        "text",
        "2002\u2013heden",
        "Periode in de bronnen-statistieken",
        130,
    ),
    (
        "methodologie.stat_years",
        "methodologie",
        "Statistiek jaren",
        "text",
        "24 jaar",
        "Aantal jaren in de bronnen-statistieken",
        140,
    ),
    (
        "methodologie.doc_types_text",
        "methodologie",
        "Documenttypen tekst",
        "textarea",
        "Documenttypen: moties, amendementen, notulen, begrotingen, commissieverslagen, jaarstukken, voorjaarsnota\u2019s, collegebrieven en raadsinformatiebrieven.",
        "Opsomming van documenttypen",
        150,
    ),
    (
        "methodologie.ai_transparency_title",
        "methodologie",
        "AI-transparantie titel",
        "text",
        "AI-transparantie",
        "Koptekst van de AI-transparantie sectie",
        160,
    ),
    (
        "methodologie.ai_does_title",
        "methodologie",
        "AI doet: titel",
        "text",
        "Wat de AI wel doet",
        "Subtitel van de 'AI doet'-lijst",
        170,
    ),
    (
        "methodologie.ai_does_list",
        "methodologie",
        "AI doet: lijst",
        "textarea",
        "Relevante documentfragmenten selecteren op basis van uw vraag\n"
        "Informatie uit meerdere bronnen samenvatten tot een coherent antwoord\n"
        "Bronverwijzingen toevoegen bij elke bewering\n"
        "Partijstandpunten en stemgedrag in context plaatsen",
        "E\u00e9n item per regel",
        180,
    ),
    (
        "methodologie.ai_doesnt_title",
        "methodologie",
        "AI doet niet: titel",
        "text",
        "Wat de AI niet doet",
        "Subtitel van de 'AI doet niet'-lijst",
        190,
    ),
    (
        "methodologie.ai_doesnt_list",
        "methodologie",
        "AI doet niet: lijst",
        "textarea",
        "Eigen meningen of waardeoordelen geven\n"
        "Informatie verzinnen die niet in de brondocumenten staat\n"
        "Documenten wijzigen of interpreteren buiten de feitelijke inhoud\n"
        "Persoonlijke gegevens van gebruikers opslaan of analyseren",
        "E\u00e9n item per regel",
        200,
    ),
    (
        "methodologie.eval_title",
        "methodologie",
        "Evaluatie titel",
        "text",
        "Evaluatie",
        "Koptekst van de evaluatie-sectie",
        210,
    ),
    (
        "methodologie.eval_intro",
        "methodologie",
        "Evaluatie intro",
        "textarea",
        "NeoDemos wordt continu ge\u00ebvalueerd op drie kernmetrieken, getest tegen een benchmark van 20 representatieve vragen:",
        "Inleidende tekst van de evaluatie-sectie",
        220,
    ),
    (
        "methodologie.eval_precision",
        "methodologie",
        "Evaluatie precisie score",
        "text",
        "0.99",
        "Score voor precisie",
        230,
    ),
    (
        "methodologie.eval_precision_label",
        "methodologie",
        "Evaluatie precisie label",
        "text",
        "Precisie",
        "Label bij de precisie-score",
        240,
    ),
    (
        "methodologie.eval_precision_desc",
        "methodologie",
        "Evaluatie precisie beschrijving",
        "text",
        "Verwijst het antwoord naar de juiste brondocumenten?",
        "Uitleg bij de precisie-score",
        250,
    ),
    (
        "methodologie.eval_faithfulness",
        "methodologie",
        "Evaluatie getrouwheid score",
        "text",
        "4.8 / 5",
        "Score voor getrouwheid",
        260,
    ),
    (
        "methodologie.eval_faithfulness_label",
        "methodologie",
        "Evaluatie getrouwheid label",
        "text",
        "Getrouwheid",
        "Label bij de getrouwheid-score",
        270,
    ),
    (
        "methodologie.eval_faithfulness_desc",
        "methodologie",
        "Evaluatie getrouwheid beschrijving",
        "text",
        "Komt het antwoord overeen met wat er in de bronnen staat?",
        "Uitleg bij de getrouwheid-score",
        280,
    ),
    (
        "methodologie.eval_completeness",
        "methodologie",
        "Evaluatie volledigheid score",
        "text",
        "2.75 / 5",
        "Score voor volledigheid",
        290,
    ),
    (
        "methodologie.eval_completeness_label",
        "methodologie",
        "Evaluatie volledigheid label",
        "text",
        "Volledigheid",
        "Label bij de volledigheid-score",
        300,
    ),
    (
        "methodologie.eval_completeness_desc",
        "methodologie",
        "Evaluatie volledigheid beschrijving",
        "text",
        "Dekt het antwoord alle relevante aspecten van de vraag?",
        "Uitleg bij de volledigheid-score",
        310,
    ),
    (
        "methodologie.eval_note",
        "methodologie",
        "Evaluatie toelichting",
        "textarea",
        "Volledigheid is bewust lager \u2014 NeoDemos geeft liever een betrouwbaar deelantwoord dan een volledig maar onzeker antwoord. Verbetering van volledigheid is een actief ontwikkeldoel.",
        "Toelichting onder de evaluatiescores",
        320,
    ),
    (
        "methodologie.limitations_title",
        "methodologie",
        "Beperkingen titel",
        "text",
        "Bekende beperkingen",
        "Koptekst van de beperkingen-sectie",
        330,
    ),
    (
        "methodologie.limitations_list",
        "methodologie",
        "Beperkingen lijst",
        "textarea",
        "AI kan fouten maken. Controleer altijd het brondocument via de bronverwijzing. Het AI-model kan fragmenten verkeerd interpreteren of onvolledige context meewegen.\n"
        "Niet alle documenten zijn even goed doorzoekbaar. Sommige oudere documenten bevatten gescande pagina\u2019s waarvan de tekst niet altijd volledig is herkend.\n"
        "OCR-kwaliteit varieert. Documenten van v\u00f3\u00f3r 2010 hebben soms lagere OCR-kwaliteit, wat invloed kan hebben op de doorzoekbaarheid.\n"
        "Geen real-time data. Er zit een vertraging van maximaal enkele uren tussen publicatie op de raadsinformatie-portal en beschikbaarheid in NeoDemos.\n"
        "Alleen Rotterdam. NeoDemos indexeert momenteel uitsluitend documenten van de Rotterdamse gemeenteraad.",
        "E\u00e9n beperking per regel (vet gedeelte + uitleg)",
        340,
    ),

    # ── Section: footer (from partials/_footer.html) ──
    (
        "footer.attribution_ai",
        "footer",
        "Footer AI-vermelding",
        "text",
        "Analyse door AI (Anthropic)",
        "AI-provider vermelding in de footer",
        10,
    ),
    (
        "footer.attribution_hosting",
        "footer",
        "Footer hosting-vermelding",
        "text",
        "Europees gehost",
        "Hosting-vermelding in de footer",
        20,
    ),
    (
        "footer.attribution_source",
        "footer",
        "Footer brondata-vermelding",
        "text",
        "Brondata: Open Raadsinformatie",
        "Brondata-vermelding in de footer",
        30,
    ),
]


def seed():
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor()

    count = 0
    for key, section, label, content_type, value, help_text, sort_order in SEED_DATA:
        cur.execute(
            """
            INSERT INTO site_content (key, section, label, content_type, value, default_value, help_text, sort_order)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (key) DO UPDATE SET
                section = EXCLUDED.section,
                label = EXCLUDED.label,
                content_type = EXCLUDED.content_type,
                default_value = EXCLUDED.default_value,
                help_text = EXCLUDED.help_text,
                sort_order = EXCLUDED.sort_order
            """,
            (key, section, label, content_type, value, value, help_text, sort_order),
        )
        count += 1

    conn.commit()
    cur.close()
    conn.close()
    print(f"Seeded {count} site_content items.")


if __name__ == "__main__":
    seed()
